### ISSUE TITLE
Where's the doc about HTMI

### ISSUE THREAD

**Issue by amirouche** [kengz/aiva#19]
The documentation links to https://github.com/kengz/aiva/tree/master/docs/HTMI.md but the link is broken same for Context Aware Knowledge Graph

**Comment by kengz** [comment]
Oops recently moved the doc to the main doc page. Forgot to update the link. Here's it for the mean time http://kengz.me/aiva/#human-turing-machine-interface

**Comment by kengz** [comment]
updated!
