### ISSUE TITLE
bin/start references mysql

### ISSUE THREAD

**Issue by dschaper** [kengz/aiva#25]
https://github.com/kengz/aiva/blob/master/bin/start#L18 looks like it still has the old `mysql` in there and will fail out.

**Comment by kengz** [comment]
Yep these 2 lines will break the Docker build. Since it's related to #24 can u replace the commands to start postgres instead?

**Comment by dschaper** [comment]
Sure, I'll add that when I get back to my development system...

**Comment by kengz** [comment]
Thank you!

**Comment by kengz** [comment]
Fixed by #24
