### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by dimoibiehg** [kengz/aiva#27]
Hi, 
When I ran this command "npm run setup", I got `'bin' is not recognized as an internal or external command, operable program or batch file.`
Any suggestion? (You can see my command line in the following).
![aiva](https://cloud.githubusercontent.com/assets/22638310/20038445/3225415a-a449-11e6-894d-aadc20bdfbe3.png)

**Comment by kengz** [comment]
Hey. A lot of the dependencies and binaries are only runnable in Linux too. I suggest using Ubuntu bash shell inside Windows 10.

**Comment by dimoibiehg** [comment]
Thanks. I've tried the Ubuntu Bash! it is not convenient in Windows 10! 
As you said, it seems just working in Linux.
