### ISSUE TITLE
About Slack in channel

### ISSUE THREAD

**Issue by GaiaAnn** [kengz/aiva#38]
I have one question about **slack**
If I add my slackbot to channel, it won't reply me.
But when I send message to slackbot directly. it works!

How can I fix it?
If I use slack adapter it can work in both channel and slackbot.
Please help me thanks :-)

**Comment by kengz** [comment]
U need to mention the bot by name in a channel, like `@aiva hello`.

**Comment by GaiaAnn** [comment]
OK! It works thanks ~
