### ISSUE TITLE
Setup failing

### ISSUE THREAD

**Issue by Mario4272** [kengz/aiva#42]
I have the Latest versions of everything on Ubuntu 17.04.  npm and node.js are latest as well.  mySQL is installed, latest version.  New Ubuntu 17.04 build.  Clean machine.

npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'setup' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle aiva@4.2.0~presetup: aiva@4.2.0
6 silly lifecycle aiva@4.2.0~presetup: no script for presetup, continuing
7 info lifecycle aiva@4.2.0~setup: aiva@4.2.0
8 verbose lifecycle aiva@4.2.0~setup: unsafe-perm in lifecycle true
9 verbose lifecycle aiva@4.2.0~setup: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/mario/git/aiva/node_modules/.bin:/home/mario/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle aiva@4.2.0~setup: CWD: /home/mario/git/aiva
11 silly lifecycle aiva@4.2.0~setup: Args: [ '-c', 'bin/setup' ]
12 silly lifecycle aiva@4.2.0~setup: Returned: code: 1  signal: null
13 info lifecycle aiva@4.2.0~setup: Failed to exec setup script
14 verbose stack Error: aiva@4.2.0 setup: `bin/setup`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid aiva@4.2.0
16 verbose cwd /home/mario/git/aiva
17 error Linux 4.10.0-32-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "setup"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error aiva@4.2.0 setup: `bin/setup`
22 error Exit status 1
23 error Failed at the aiva@4.2.0 setup script 'bin/setup'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the aiva package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     bin/setup
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs aiva
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls aiva
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Mario4272** [comment]
Disregard - Figured it out.  Security issues with mysql.  Issues weren't in the log they were in the terminal window.  thanks.

**Comment by kengz** [comment]
cool
