### ISSUE TITLE
Error = Target script does not exist: run.js

### ISSUE THREAD

**Issue by llwp** [kengz/aiva#8]
Present on my system (ubuntu trusty) installed following all available documentation.
Also verified as an issue as same thing happens here: https://tonicdev.com/npm/jarvis-bot

I haven't yet found the construct or docs for what is needed in run.js in this particular package.

Any suggestions?

![screenshot 2016-07-17 at 15 41 23](https://cloud.githubusercontent.com/assets/9566542/16902717/fac2b074-4c34-11e6-807a-959424310da6.png)

**Comment by kengz** [comment]
Hey, the npm version is Jarvis v1.0, which is a legacy release (can't be used with v2). Please see [the note](https://github.com/kengz/aiva#legacy-releases)
