### ISSUE TITLE
Docker run... now what?

### ISSUE THREAD

**Issue by llwp** [kengz/aiva#9]
Alright, ubuntu install got me maybe 90% of the way but as noted in previous issue: no joy (yet).
So, a-docker-ing we go.

Got it online.  Easy peasy.

But I end up in the /opt/aiva directory but nothing is there.  Is the :latest version not ready any longer?  How do I use this once it is running?

Thanks!

**Comment by kengz** [comment]
Hi, yes Docker has a lot of good resources out there. 

Just to make sure, if you're on Macbook, you need to have the VM started. The full steps are [listed here.](http://kengz.me/aiva/#setup-run)

In steps:
1. `git clone YOUR FORK` of this repo and `cd` into the project root
2. `docker pull kengz/aiva` to pull the Docker image
3. `npm start` (assuming your Docker machine is up)

For more [commands please see here](http://kengz.me/aiva/#development-guide), might give you more insights.

---

As for the docker image, it mounts on the Docker data volume when u run the start command. You can only look inside the VM when it's started, via that same Bash session.

Though, the Docker data volume syncs to the AIVA project folder root, from where you run the command `npm start`. So any file changes that happen on your host machine is sync with the mounted data volume in the VM.

Let me know if you get it working!
